### ISSUE TITLE
[BUG] - Short desc

### ISSUE THREAD

**Issue by SakshamT2005** [Saamstep/modmail#56]
C:\Users\Saksham\Desktop\New folder\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
embed.footer.icon_url: Scheme "null" is not supported. Scheme must be one of ('http', 'https').
embeds[0].footer.icon_url: Scheme "null" is not supported.

I'm getting this error while running the code i guess you should upgrade discord.js module as v12 is no longer supported

**Comment by Saamstep** [comment]
Hey there! Due to the poor performance and optimization of ModMail, I recently have been working on a full re-code and I am super excited to share it with everyone soon! Because of this, I will not be providing much support for older versions due to the large number of problems that existed. I will be sure to notify everyone when the full version of v3 is released.
