### ISSUE TITLE
most ticket commands are not working

### ISSUE THREAD

**Issue by viper-client** [Saamstep/modmail#58]
well i noticed that the `snippets` command is working but noone can use the created snippets as we tried many time by `snippet` with/without prefix with all possible syntaxes but not working (of course both in ticket and non-ticket channels) , also the `close` and `cmds` commands are the same but others looks ok

also no console error at all, seems that commands are not defined at all

> replit
> Node JS v12.22.6
> NPM v6.14.15
> discord.js v12.5.2
> bot v2.1.2
> no error

what should i do? is it a bug or i missed something?

**Comment by Saamstep** [comment]
Hey there! Due to the poor performance and optimization of ModMail, I recently have been working on a full re-code and I am super excited to share it with everyone soon! Because of this, I will not be providing much support for older versions due to the large number of problems that existed. I will be sure to notify everyone when the full version of v3 is released.
